apiVersion: v1
kind: Service
metadata:
  name: ele-osms-php
  namespace: ecommerce
  labels:
    app: php-web
spec:
  selector:
    app: osms-php
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: ele-osms-mysql
  namespace: ecommerce
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    nodePort: 30306
---
apiVersion: v1
kind: Service
metadata:
  name: ele-osms-phpmyadmin
  namespace: ecommerce
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30082